### ISSUE TITLE
Question about valid range for aBayes

### ISSUE THREAD

**Issue by kgori** [stephaneguindon/phyml#14]
I left this comment in the google group, too.

Occasionally I see values of 0 for aBayes branch support. As far as I know the aBayes value for a node should be in the range [0.333..., 1], provided the likelihood of the current node arrangement is higher than (or approx. equal to) the 2 NNI rearrangements. Compute_Likelihood_Ratio_Test in alrt.c has a condition that sets the support value to 0 if all likelihoods are approximately equal (see line 316 in commit 6c6e4ad). Do you think that in the case of aBayes the support value should be calculated as normal, even if the three likelihoods are equal? Or even if ln0 is lower than ln1 or ln2, although in this case the tree topology can be optimised further?

Regards,
Kevin

**Comment by stephaneguindon** [comment]
Hi Kevin,

I agree that setting the probability to zero in case ln0 < max(ln1,ln2)
does not really stack up from a mathematical point of view. From a
more pragmatic perspective though, one may argue that since the
current configuration is sub-optimal, we know for sure that it
must be replaced by one of the other two configurations. Hence
the zero probability.

The case ln0=ln1=ln2 arises when the corresponding edge has
length 0.0. In that particular situation, one may argue that none
of the three configurations actually exists, hence the probability
zero.

Hope it makes sense,

-Stephane-
