### ISSUE TITLE
Missing install script?

### ISSUE THREAD

**Issue by roohif** [stephaneguindon/phyml#2]
Hi,

This is my first ever git clone, so I don't know if this is my error or yours :)

configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

Should this script be in the repo, or is it something that I should have somewhere? I'm on MacOSX v13.4.0 (Mac Mini).

**Comment by jjsoliveira** [comment]
Hello,

I have this same problem now. Do you know why is it happening?

**Comment by wookietreiber** [comment]
Actually, you should not add these autotools-related files like `compile`, `install-sh`, etc. to the repository.

The common procedure is as follows: If you clone the repository, you should have autotools installed, i.e. autoconf, automake, libtool, etc. and execute `autoreconf -fi`. This will generate all of these required files from your local autotools installation. Then you can start the usual `./configure && make` procedure.

You should, however, include these autotools-related files in the distribution tar-ball. This tar-ball is usually created via `make dist`.

It is also quite common to put this `autoreconf -fi` stuff in an `autogen.sh` script which is included in the repository. This *auto-generation* scripts purpose is to set up the project from its repository state to the distribution-ready state. `autoreconf -fi`, i.e. `autoreconf --force --install` forces a complete autotools reconfiguration based on your current setup, OS and everything and installs all missing files. This is very recommended if you already checked out the repository before and have some stale / out-dated versions of these files from an older commit or even different branch which may or may not have different `configure.ac` or `Makefile.am` files. By executing this `autogen.sh` script you make sure your generated `configure` script and `Makefile.in`s are set up as the developers of the project intend.

Thus, to summarize, if you ...

1.  build from repository, you execute:

        ./autogen.sh
        ./configure
        make
        make install

2.  build from release tar-ball, you do the same as (1) except for the `autogen.sh` stuff, because all required files are included in the tar-ball and expected to be up-to-date, created by the person who just released this tar-ball.

The purpose of this differentiation is that if you get a release tar-ball, you need only a compiler and all dependencies to build the project, but not autotools, whereas if you clone the repository you are more or less *expected* to have a developers setup, including autotools.

**Comment by jjsoliveira** [comment]
Ok wookietreiber, I am gonna do this! thanks a lot!
